    <main>
        <!-- HEADER ENDS --> 
        <div class="container-fluid">
            <section id="myCarousel" class="carousel slide">


                <!-- Wrapper for Slides -->
                <div id="mainImg" class="carousel-inner">
                    <div class="item active">
                        <!-- Set the first background image using inline CSS below. -->
<!--                        <img src="/front/img/slide1.png">                   -->
                        <img src="/front/img/test/slide1.jpg"> 
                    </div>
                    <div class="item">
                        <img src="/front/img/test/slide2.jpg" alt=""/>
                    </div>
                    <div class="item">
                        <img src="/front/img/test/slide3.jpg" alt=""/>
                    </div>
                    <div class="item">
                        <img src="/front/img/test/slide4.jpg" alt=""/>
                    </div>
                    <div class="item">
                        <img src="/front/img/test/slide5.jpg" alt=""/>
                    </div>
<!--                    <div class="item">
                        <img src="/front/img/test/slide8.jpg" alt=""/>
                    </div>
                    <div class="item">
                        <img src="/front/img/test/slide9.jpg" alt=""/>
                    </div>
                    <div class="item">
                        <img src="/front/img/test/slide10.jpg" alt=""/>
                    </div>
                    <div class="item">
                        <img src="/front/img/test/slide11.jpg" alt=""/>
                    </div>
                    <div class="item">
                        <img src="/front/img/test/slide12.jpg" alt=""/>
                    </div>
                    <div class="item">
                        <img src="/front/img/test/slide13.jpg" alt=""/>
                    </div>
                    <div class="item">
                        <img src="/front/img/test/slide14.jpg" alt=""/>
                    </div>
                    <div class="item">
                        <img src="/front/img/test/slide15.jpg" alt=""/>
                    </div>-->
                    
                </div>
                <!-- Controls -->
                <a class="left carousel-control" href="#myCarousel" data-slide="prev">
                    <span class="icon-prev"></span>
                </a>
                <a class="right carousel-control" href="#myCarousel" data-slide="next">
                    <span class="icon-next"></span>
                </a>
            </section> 
        </div>

        <section id="performance" class="performance text-center">
            <div class="container">         
                <div class="row">
                    <div class=" col-sm-6 col-md-3">
                        <article class="gmo">                            
                            <figure>
                                <img src="/front/img/test/circle1.jpg" class="img-responsive img-circle" >
                            </figure> 
                            <h2 class="text-uppercase">GMO-FREE<br><span>GUARANTEED</span></h2> 
                            <p>Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet..</p>
                        </article>  

                    </div>

                    <div class=" col-sm-6 col-md-3">
                        <article class="premium text-center">                            
                            <figure>
                                <img src="/front/img/test/circle2.jpg" class="img-responsive img-circle">
                            </figure>
                            <h2 class="text-uppercase">PREMIUM<br><span>QUALITY</span></h2> 
                            <p>Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet..</p>
                        </article> 
                    </div>
                    <div class=" col-sm-6 col-md-3">
                        <article class="organic text-center">                            
                            <figure>
                                <img src="/front/img/test/circle3.jpg" class="img-responsive img-circle">
                            </figure>
                            <h2 class="text-uppercase">ORGANIC<br><span>100% HEALTHY</span></h2> 

                            <p>Aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum.</p>
                        </article> 

                    </div>
                    <div class=" col-sm-6 col-md-3">
                        <article class="price text-center">                            
                            <figure>
                                <img src="/front/img/test/circle4.jpg" class="img-responsive img-circle" >
<!--                                style="border:5px solid #ffffff;"-->
                            </figure>
                            <h2 class="text-uppercase">BEST PRICE<br><span>ALWAYS</span></h2> 

                            <p>Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor.</p>
                        </article> 

                    </div>
                </div>
            </div>
        </section>

        <section class="gallery">

            <div class="text-center"> 

                <!-- Nav tabs -->
                <ul class="nav nav-tabs text-center" role="tablist">
                    <li role="presentation" class="active"><a href="#all" aria-controls="all" role="tab" data-toggle="tab">ALL</a></li>
                    <li role="presentation"><a href="#fruits" aria-controls="fruits" role="tab" data-toggle="tab">FRUITS</a></li>
                    <li role="presentation"><a href="#vegetables" aria-controls="vegetables" role="tab" data-toggle="tab">VEGETABLES</a></li>
                    <li role="presentation"><a href="#berries" aria-controls="berries" role="tab" data-toggle="tab">BERRIES</a></li>
                    <li role="presentation"><a href="#food" aria-controls="food" role="tab" data-toggle="tab">FOOD</a></li>
                    <li role="presentation"><a href="#planting" aria-controls="planting" role="tab" data-toggle="tab">PLANTING</a></li>
                    <li role="presentation"><a href="#organic" aria-controls="organic" role="tab" data-toggle="tab">ORGANIC</a></li>
                    <li role="presentation"><a href="#selecting" aria-controls="selecting" role="tab" data-toggle="tab">SELECTING</a></li>
                </ul>

                <!-- Tab panes -->
                <div class="tab-content">

                    <div role="tabpanel" class="tab-pane active row" id="all">
                        <article class="col-xs-3 col-md-3">  
                            <figure>
                                <img src="/front/img/gallery1.png" alt=""/>
                            </figure>
                        </article>

                        <article class="col-xs-3 col-md-3">
                            <figure>
                                <img src="/front/img/gallery2.png" alt=""/>
                            </figure>
                        </article>
                        <article class="col-xs-3 col-md-3">
                            <figure>    
                                <img src="/front/img/gallery3.png" alt=""/>
                            </figure>
                        </article>
                        <article class="col-xs-3 col-md-3">
                            <figure>
                                <img src="/front/img/gallery4.png" alt=""/>
                            </figure>
                        </article>
                    </div>               

                    <div role="tabpanel" class="tab-pane" id="fruits">
                        <article class="col-xs-3 col-md-3"> 
                            <figure>
                                <img src="/front/img/gallery2.png" alt=""/>
                            </figure>
                        </article>
                        <article class="col-xs-3 col-md-3">
                            <figure>
                                <img src="/front/img/gallery3.png" alt=""/>
                            </figure>
                        </article>                        
                        <article class="col-xs-3 col-md-3">
                            <figure>
                                <img src="/front/img/gallery4.png" alt=""/>
                            </figure>
                        </article>
                        <article class="col-xs-3 col-md-3">
                            <figure>
                                <img src="/front/img/gallery1.png" alt=""/>
                            </figure>
                        </article>                    
                    </div>                                        
                    <div role="tabpanel" class="tab-pane" id="vegetables">
                        <article class="col-xs-3 col-md-3"> 
                            <figure>
                                <img src="/front/img/gallery4.png" alt=""/>
                            </figure>
                        </article>                       
                        <article class="col-xs-3 col-md-3">
                            <figure>
                                <img src="/front/img/gallery1.png" alt=""/>
                            </figure>
                        </article>
                        <article class="col-xs-3 col-md-3">
                            <figure>
                                <img src="/front/img/gallery3.png" alt=""/>
                            </figure>
                        </article>
                        <article class="col-xs-3 col-md-3">
                            <figure>
                                <img src="/front/img/gallery2.png" alt=""/>
                            </figure>
                        </article>  
                    </div>
                    <div role="tabpanel" class="tab-pane" id="berries">
                        <article class="col-xs-3 col-md-3"> 
                            <figure>
                                <img src="/front/img/gallery3.png" alt=""/>
                            </figure>
                        </article>
                        <article class="col-xs-3 col-md-3">
                            <figure>
                                <img src="/front/img/gallery4.png" alt=""/>
                            </figure>
                        </article>
                        <article class="col-xs-3 col-md-3">
                            <figure>
                                <img src="/front/img/gallery1.png" alt=""/>
                            </figure>
                        </article>
                        <article class="col-xs-3 col-md-3">
                            <figure>
                                <img src="/front/img/gallery2.png" alt=""/>
                            </figure>
                        </article>  
                    </div>
                    <div role="tabpanel" class="tab-pane" id="food">
                        <article class="col-xs-3 col-md-3"> 
                            <figure>
                                <img src="/front/img/gallery3.png" alt=""/>
                            </figure>
                        </article>                        
                        <article class="col-xs-3 col-md-3">
                            <figure>
                                <img src="/front/img/gallery2.png" alt=""/>
                            </figure>
                        </article>
                        <article class="col-xs-3 col-md-3">
                            <figure>
                                <img src="/front/img/gallery1.png" alt=""/>
                            </figure>
                        </article>
                        <article class="col-xs-3 col-md-3">
                            <figure>
                                <img src="/front/img/gallery4.png" alt=""/>
                            </figure>
                        </article>
                    </div>
                    <div role="tabpanel" class="tab-pane" id="planting">
                        <article class="col-xs-3 col-md-3"> 
                            <figure>
                                <img src="/front/img/gallery1.png" alt=""/>
                            </figure>
                        </article>                        
                        <article class="col-xs-3 col-md-3">
                            <figure>
                                <img src="/front/img/gallery4.png" alt=""/>
                            </figure>
                        </article>
                        <article class="col-xs-3 col-md-3">
                            <figure>
                                <img src="/front/img/gallery2.png" alt=""/>
                            </figure>
                        </article>
                        <article class="col-xs-3 col-md-3">
                            <figure>
                                <img src="/front/img/gallery3.png" alt=""/>
                            </figure>
                        </article>
                    </div>
                    <div role="tabpanel" class="tab-pane" id="organic">
                        <article class="col-xs-3 col-md-3">
                            <figure>
                                <img src="/front/img/gallery3.png" alt=""/>
                            </figure>
                        </article>                        
                        <article class="col-xs-3 col-md-3">
                            <figure>
                                <img src="/front/img/gallery1.png" alt=""/>
                            </figure>
                        </article>
                        <article class="col-xs-3 col-md-3">
                            <figure>
                                <img src="/front/img/gallery4.png" alt=""/>
                            </figure>
                        </article>
                        <article class="col-xs-3 col-md-3">
                            <figure>
                                <img src="/front/img/gallery2.png" alt=""/>
                            </figure>
                        </article>
                    </div>
                    <div role="tabpanel" class="tab-pane" id="selecting">
                        <article class="col-xs-3 col-md-3">
                            <figure>
                                <img src="/front/img/gallery2.png" alt=""/>
                            </figure>
                        </article>                        
                        <article class="col-xs-3 col-md-3">
                            <figure>
                                <img src="/front/img/gallery1.png" alt=""/>
                            </figure>
                        </article>
                        <article class="col-xs-3 col-md-3">
                            <figure>
                                <img src="/front/img/gallery4.png" alt=""/>
                            </figure>
                        </article>
                        <article class="col-xs-3 col-md-3">
                            <figure>
                                <img src="/front/img/gallery3.png" alt=""/>
                            </figure>
                        </article>
                    </div>                                                                     
                </div>
            </div>
        </section>
        <section class="about">
            <div class="container-fluid">
                <div class="row">
                    <article class="col-xs-12 col-sm-6">
                        <figure>
                            <img src="/front/img/about.png" alt="" class="img-responsive">
                        </figure>
                    </article>
                    <article class="col-xs-12 col-sm-6 aboutText">                        
                        <h2>About                           
                        </h2>
                        <h3>our company</h3>
                        <p class="description">Invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet.</p>
                        <article class="borderGray">

                            <img src="/front/img/clock.png" alt=""/>

                            <p>35 YEARS EXPERIENCE IN GARDENING BUSINESS</P>
                        </article>
                        <article class="borderGray">

                            <img src="/front/img/folder.png" alt=""/>

                            <p>TONES OFF OFFERS & SERVICES</P>
                        </article> 
                        <article class="borderGray">

                            <img src="/front/img/people.png" alt=""/>

                            <p>BEST PROFESSIONALS ALL OVER THE WORLD</P>

                        </article>
                </div>
            </div>
        </section>      
        <section class="customers">
            <div class="container">
                <div class="row">
                    <article class="col-sm-6 ">
                        <div class="arrow_box">
                            <div class="row">
                                <div class="col-xs-3 text-center">
                                    <span class="fa fa-quote-left"></span>
                                </div>
                                <div class="col-xs-9 comment">   
                                    <p>Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum.</p>  
                                </div>
                            </div> 
                        </div>
                        <div class="arrow-down"></div>
                        <div class="row">
                            <article class="col-xs-5">
                                <figure>
                                    <img src="/front/img/customer1.png" alt="" class="img-responsive"/>
                                </figure>
                            </article>
                            <article class="col-xs-7 review">
                                <h2>Francis M. Hartzell<br>
                                    <span>CUSTOMER</span>                         
                                </h2> 
                            </article>
                        </div>
                    </article>
                    <article class="col-sm-6 ">
                        <div class="arrow_box">
                            <div class="row">
                                <div class="col-xs-3 text-center">
                                    <span class="fa fa-quote-left"></span>
                                </div>
                                <div class="col-xs-9 comment">   
                                    <p>Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum.</p>  
                                </div>
                            </div> 
                        </div>
                        <div class="arrow-down"></div>
                        <div class="row">
                            <article class="col-xs-5">
                                <figure>
                                    <img src="/front/img/customer1.png" alt="" class="img-responsive"/>
                                </figure>
                            </article>
                            <article class="col-xs-7 review">
                                <h2>Francis M. Hartzell<br>
                                    <span>CUSTOMER</span>                         
                                </h2> 
                            </article>
                        </div>
                    </article>
                </div>
            </div>  
        </section> 

        <section class="latestNews text-center">
            <div class="container"> 
                <h2>Our<br>
                    <span>Latest News</span>
                </h2>
                <div class="row">
                    <div class="col-sm-xs col-sm-4">
                        <div class="thumbnail">
                            <figure>
                                <a href="#"> <img src="/front/img/news1.png" alt="" class="img-responsive"/></a>
                            </figure>
                            <div class="caption">
                                <p>23.03.2016 BY ADMIN</p>
                                <h3><a href="#">Lorem ipsum dolor sit consetetur</a></h3>
                                <p>Consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna.</p>                           
                            </div>
                            <div class="row icons">
                                <article class=" col-xs-4 border">
                                    <p><span class="glyphicon glyphicon-eye-open"></span><br>
                                        23,527
                                    </p>
                                </article>
                                <article class=" col-xs-4 border">
                                    <p><span class="glyphicon glyphicon-heart-empty"></span><br>
                                        4,783
                                    </p>
                                </article>
                                <article class=" col-xs-4 border">
                                    <p><span class="glyphicon glyphicon-comment"></span><br>
                                        3,896
                                    </p>
                                </article> 
                            </div> 
                        </div>


                    </div>
                    <div class="col-sm-xs col-sm-4">
                        <div class="thumbnail">
                            <figure>
                                <a href="#"><img src="/front/img/news2.png" alt="" class="img-responsive"/></a>
                            </figure>
                            <div class="caption">
                                <p>15.03.2016 BY USER</p>
                                <h3><a href="#">Sadipscing elitr sed diam nonumy</a></h3>
                                <p>Aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum.</p>                           
                            </div>
                            <div class="row icons">
                                <article class=" col-xs-4 border">
                                    <p><span class="glyphicon glyphicon-eye-open"></span><br>
                                        15,754
                                    </p>
                                </article>
                                <article class=" col-xs-4 border">
                                    <p><span class="glyphicon glyphicon-heart-empty"></span><br>
                                        1,043
                                    </p>
                                </article>
                                <article class=" col-xs-4 border">
                                    <p><span class="glyphicon glyphicon-comment"></span><br>
                                        2,953
                                    </p>
                                </article> 
                            </div> 
                        </div> 
                    </div> 
                    <div class="col-sm-xs col-sm-4">
                        <div class="thumbnail">
                            <figure>
                                <a href="#"><img src="/front/img/news3.png" alt="" class="img-responsive"/></a>
                            </figure>
                            <div class="caption">
                                <p>15.03.2016 BY GUEST</p>
                                <h3><a href="#">Sadipscing elitr sed diam nonumy</a></h3>
                                <p>Aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum.</p>                           
                            </div>
                            <div class="row icons">
                                <article class=" col-xs-4 border">
                                    <p><span class="glyphicon glyphicon-eye-open"></span><br>
                                        54,476
                                    </p>
                                </article>
                                <article class=" col-xs-4 border">
                                    <p><span class="glyphicon glyphicon-heart-empty"></span><br>
                                        4,576
                                    </p>
                                </article>
                                <article class=" col-xs-4 border">
                                    <p><span class="glyphicon glyphicon-comment"></span><br>
                                        3,345
                                    </p>
                                </article> 
                            </div> 
                        </div>
                    </div>
                </div>
            </div>
        </section> 
        <section class="contact">
            <div class="container-fluid text-center">
                <h2>You like organic eco food? Buy now!<br>
                    <span>Just contact us!</span>                    
                </h2>
                <a href="#" class="btn btn-primary" role="button">PURCHASE</a>                                          
            </div>
        </section>


        <section class="advantages">
            <div class="container "> 
                <div class="text-center">
                    <h2>Our<br>
                        <span>Advantages</span>
                    </h2>
                </div>
                <div class="row">


                    <div class=" col-xs-12  col-md-4">
                        <div class="media">
                            <div class="media-left">
                                <a href="#">
                                    <img src="/front/img/advantages1.png" alt=""/>
                                </a>
                            </div>
                            <div class="media-body">
                                <h4 class="media-heading">Reputable Company</h4>
                                <p>Lorem ipsum dolor sit amet onsetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt.</p>
                            </div>
                        </div>               
                    </div>
                    <div class="col-xs-12  col-md-4">
                        <div class="media">
                            <div class="media-left">
                                <a href="#">
                                    <img src="/front/img/advantages2.png" alt=""/>
                                </a>
                            </div>
                            <div class="media-body">
                                <h4 class="media-heading">Free Consultations</h4>
                                <p>Lorem ipsum dolor sit amet onsetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt.</p>
                            </div>
                        </div>
                    </div>
                    <div class="col-xs-12 col-md-4">
                        <div class="media">
                            <div class="media-left">
                                <a href="#">
                                    <img src="/front/img/advantages3.png" alt=""/>
                                </a>
                            </div>
                            <div class="media-body">
                                <h4 class="media-heading">Day Scheduling</h4>
                                <p>Lorem ipsum dolor sit amet onsetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt</p>
                            </div>
                        </div>
                    </div>  
                    <div class="col-xs-12 col-md-4">
                        <div class="media">
                            <div class="media-left">
                                <a href="#">
                                    <img src="/front/img/advantages4.png" alt=""/>
                                </a>
                            </div>
                            <div class="media-body">
                                <h4 class="media-heading">Reputable Company</h4>
                                <p>Lorem ipsum dolor sit amet onsetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt.</p>
                            </div>
                        </div> 
                    </div>

                    <div class="col-xs-12 col-md-4">
                        <div class="media">
                            <div class="media-left">
                                <a href="#">
                                    <img src="/front/img/advantages5.png" alt=""/>
                                </a>
                            </div>
                            <div class="media-body">
                                <h4 class="media-heading">Licensed & Insured</h4>
                                <p>Lorem ipsum dolor sit amet onsetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt.</p>
                            </div>
                        </div> 
                    </div>
                    <div class="col-xs-12 col-md-4">
                        <div class="media">
                            <div class="media-left">
                                <a href="#">
                                    <img src="/front/img/advantages6.png" alt=""/>
                                </a>
                            </div>
                            <div class="media-body">
                                <h4 class="media-heading">Dependable Services</h4>
                                <p>Lorem ipsum dolor sit amet onsetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt.</p>
                            </div>
                        </div> 
                    </div>
                </div>       
        </section>
        <section class="informations">
            <div class="container">
                <div class="row">
                    <article class="col-xs-12 col-sm-6 col-md-3 address">
                        <h2>ADDRESS</h2>
                        <p>2661 Mapleview Drive</p>
                        <p>Tarpon Springs, FL 34689</p>
                    </article>
                    <article class="col-xs-12 col-sm-6 col-md-3 hours">
                        <h2>HOURS</h2>
                        <p>Weekdays: <span>9:00-18:00</span> </p>
                        <p>Saturday: <span>11:00-15:00</span></p>
                    </article>
                    <article class="col-xs-12 col-sm-6 col-md-3 phone">
                        <h2>PHONE</h2>
                        <p>Phone:<span> 727-937-3797</span></p>
                        <p>  Fax: <span>863-256-5533</span></p>                      
                    </article>
                    <article class="col-xs-12 col-sm-6 col-md-3 email">
                        <h2>EMAIL</h2>
                        <p><a href="mailto:example@mail.com">example@mail.com</a></p>                     
                    </article>
                </div> 
            </div>
        </section>
        <section class="map">

            <iframe src="https://www.google.com/maps/embed?pb=!1m14!1m12!1m3!1d22638.214543463546!2d20.42206543162841!3d44.826111204134136!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!5e0!3m2!1sen!2srs!4v1470981890279" frameborder="0" style="border:0" allowfullscreen></iframe>

        </section>
        
    </main>