<?php
    $this->headTitle($this->sitemapPage['title']);
    $this->headMeta()->appendName('description', $this->sitemapPage['description']);
?>


    <section class="smallNav"> 
        <div class="container-fluid">
            <div class="row">
                <div class="col-xs-12 text-center">
                    <h2><a href="">Gallery</a></h2>
                </div>
                <div class="col-xs-12 text-center">
                    <ul class="simplefilterFirst">     
                        <li role="presentation" class="active"><a href="index.html">HOMEPAGE</a></li>
                        <li role="presentation"><a href="contacts.html">GALLERY</a></li>                   
                    </ul> 
                </div>
            </div>  
        </div> 
    </section>  

<!--    <div id="highlighted">
        <div class="container">
            <div class="header">
                <h2 class="page-title">
                    <span><?php echo $this->escape($this->sitemapPage['title']); ?></span>
                    <small><?php echo $this->escape($this->sitemapPage['title']); ?></small>
                </h2>
            </div>
        </div>
    </div>-->

    <div id="content">
        <div class="container portfolio">
            <!--Portfolio items-->
            <ul class="thumbnails row block projects" id="quicksand">
                <?php foreach ($this->photoGalleries as $photoGallery) { ?>
                    <li class="col-md-4 print" data-id="1" data-type="print">
                        <div class="">
                            <div class="project">
                                <a class="lnk-polaroid" href="<?php echo $this->photoGalleryUrl($photoGallery); ?>">
                                    <img src="<?php echo $this->photoGalleryLeadingPhotoUrl($photoGallery); ?>" alt="<?php echo $this->escape($photoGallery['title']); ?>" class="img-polaroid img-responsive" />
                                </a>
                                <h3 class="title">
                                    <a href="<?php echo $this->photoGalleryUrl($photoGallery); ?>"><?php echo $this->escape($photoGallery['title']); ?></a>
                                </h3>
                                <p class="muted"><?php echo $this->escape($photoGallery['description']); ?></p>
                            </div>
                        </div>
                    </li>
                <?php } ?>
            </ul>
        </div>
    </div>