<?php
    $this->headTitle('Portfolios - Edit Portfolio');
    
    $form = $this->form;
    $form->setElementDecorators(array('ViewHelper'));
?>



    <div class="page-header">
        <h1>Portfolios <small>Edit Portfolio</small></h1>
    </div>

    <div class="row">
        <div class="col-lg-12">
            <?php echo $this->systemMessagesHtml($this->systemMessages);?>
        </div>
    </div>

    <div class="row">
        <div class="col-lg-12">
            <div class="panel panel-default">
                <div class="panel-heading text-right">
                    <div class="btn-group" role="group" aria-label="...">
                        <a href="
                                <?php echo $this->url(array('controller' => 'admin_portfolios', 'action' => 'index'), 'default', true); ?>
                           " 
                           class="btn btn-default" ><i class="glyphicon glyphicon-arrow-left"></i> Back to all portfolios</a>
                    </div>
                </div>
                <div class="panel-body">
                    <form class="form-horizontal" method="post" enctype="multipart/form-data">
                        <input type="hidden" name="task" value="update">

                        <fieldset>
                            <!-- Form Name -->
                            <legend>Edit Portfolio - <?php echo $this->escape($this->portfolio['title'] . ' ' . $this->portfolio['data_categories']); ?> </legend>

                            <!-- Text input-->
                            <div class="form-group">
                                <label class="col-md-4 control-label" for="title">Title</label>  
                                <div class="col-md-4">
                                    <?php
                                        echo $form->getElement('title')->setAttribs(array(
                                            'class' => 'form-control input-md',
                                            'placeholder' => 'Enter portfolio\'s first name',
                                            'id' => 'title',
                                            'required' => 'required'
                                        ));
                                    ?>
                                    <span class="help-block">min 3, max 255 cgaracters</span>  
                                </div>
                                <div class="col-md-4">
                                    <?php if ($form->getElement('title')->hasErrors()) { ?>
                                        <div class="has-error">
                                            <?php foreach ($form->getElement('title')->getMessages() as $message) { ?>
                                                <p class="help-block"><?php echo $this->escape($message); ?></p>
                                            <?php } ?>
                                        </div>
                                    <?php } ?>
                                </div>
                            </div>

                            <!-- Text input-->
                            <div class="form-group">
                                <label class="col-md-4 control-label" for="data_categories">data_categories</label>  
                                <div class="col-md-4">
                                    <?php
                                        echo $form->getElement('data_categories')->setAttribs(array(
                                            'class' => 'form-control input-md',
                                            'placeholder' => 'Enter portfolio\'s data_categories',
                                            'id' => 'data_categories',
                                            'required' => 'required'
                                        ));
                                    ?>
                                    <span class="help-block">min 3, max 255 characters</span>  
                                </div>
                                <div class="col-md-4">
                                    <?php if ($form->getElement('data_categories')->hasErrors()) { ?>
                                        <div class="has-error">
                                            <?php foreach ($form->getElement('data_categories')->getMessages() as $message) { ?>
                                                <p class="help-block"><?php echo $this->escape($message); ?></p>
                                            <?php } ?>
                                        </div>
                                    <?php } ?>
                                </div>
                            </div>

                            <!-- Text input-->
                            <div class="form-group">
                                <label class="col-md-4 control-label" for="">characteristic1</label>  
                                <div class="col-md-4">
                                    <?php
                                        echo $form->getElement('characteristic1')->setAttribs(array(
                                            'class' => 'form-control input-md',
                                            'placeholder' => 'Enter portfolio\'s characteristic1',
                                            'id' => 'characteristic1',
                                            'required' => 'required'
                                        ));
                                    ?>

                                    <span class="help-block">characteristic1</span>  
                                </div>
                                <div class="col-md-4">
                                    <?php if ($form->getElement('characteristic1')->hasErrors()) { ?>
                                        <div class="has-error">
                                            <?php foreach ($form->getElement('characteristic1')->getMessages() as $message) { ?>
                                                <p class="help-block"><?php echo $this->escape($message); ?></p>
                                            <?php } ?>
                                        </div>
                                    <?php } ?>
                                </div>
                            </div>

                            <!-- Text input-->
                            <div class="form-group">
                                <label class="col-md-4 control-label" for="">characteristic2</label>  
                                <div class="col-md-4">
                                    <?php
                                        echo $form->getElement('characteristic2')->setAttribs(array(
                                            'class' => 'form-control  input-md',
                                            'id' => 'characteristic2'
                                        ));
                                    ?>

                                    <span class="help-block">characteristic2</span>  
                                </div>
                                <div class="col-md-4">
                                    <?php if ($form->getElement('characteristic2')->hasErrors()) { ?>
                                        <div class="has-error">
                                            <?php foreach ($form->getElement('characteristic2')->getMessages() as $message) { ?>
                                                <p class="help-block"><?php echo $this->escape($message); ?></p>
                                            <?php } ?>
                                        </div>
                                    <?php } ?>
                                </div>
                            </div>

                            <!-- Textarea -->
                            <div class="form-group">
                                <label class="col-md-4 control-label" for="description">description</label>
                                <div class="col-md-4"> 
                                    <?php
                                        echo $form->getElement('description')->setAttribs(array(
                                            'class' => 'form-control',
                                            'id' => 'description',
                                            'rows' => '12'
                                        ));
                                    ?>

                                </div>
                                <div class="col-md-4">
                                    <?php if ($form->getElement('description')->hasErrors()) { ?>
                                        <div class="has-error">
                                            <?php foreach ($form->getElement('description')->getMessages() as $message) { ?>
                                                <p class="help-block"><?php echo $this->escape($message); ?></p>
                                            <?php } ?>
                                        </div>
                                    <?php } ?>
                                </div>
                            </div>
                            
                            
                                
                            
                            <div class="form-group">
                                <label class="col-md-4 control-label" for="description">multiple</label>
                                <div class="col-md-4"> 
                                    
                                      
                                </div>
                                <div class="col-md-4">
                                    <?php if ($form->getElement('description')->hasErrors()) { ?>
                                        <div class="has-error">
                                            <?php foreach ($form->getElement('description')->getMessages() as $message) { ?>
                                                <p class="help-block"><?php echo $this->escape($message); ?></p>
                                            <?php } ?>
                                        </div>
                                    <?php } ?>
                                </div>
                            </div>

                            <div class="form-group">
                                <label class="col-md-4 control-label" for="portfolio_photo">Photo</label>
                                <div class="col-md-4">
                                    <div>
                                        <a href="#" class="thumbnail">
                                            <img src="<?php echo $this->portfolioImgUrl($this->portfolio); ?>">
                                        </a>
                                    </div>

                                    <input type="file" name="portfolio_photo" id="portfolio_photo" class="form-control input-md">
                                    <span class="help-block">change photo</span>
                                </div>

                                <div class="col-md-4">
                                    <?php if ($form->getElement('portfolio_photo')->hasErrors()) { ?>
                                        <div class="has-error">
                                            <?php foreach ($form->getElement('portfolio_photo')->getMessages() as $message) { ?>
                                                <p class="help-block"><?php echo $this->escape($message); ?></p>
                                            <?php } ?>
                                        </div>
                                    <?php } ?>
                                </div>
                            </div>
                            
                            
                            <!-- Button (Double) -->
                            <div class="form-group">
                                <label class="col-md-4 control-label" for="new_portfolio_cancel"></label>
                                <div class="col-md-4 text-right">
                                    <a href=" <?php echo $this->url(array('controller' => 'admin_portfolios', 'action' => 'index'), 'default', 'true'); ?> " id="new_portfolio_cancel" name="new_portfolio_cancel" class="btn btn-default" >Cancel</a>
                                    <button type="submit" id="new_portfolio_submit" name="new_portfolio_submit" class="btn btn-success">Save</button>
                                </div>
                            </div>

                        </fieldset>
                    </form>
                </div>
            </div>
        </div>
    </div>
                                  
<select id="example-getting-started" multiple="multiple">
                                        <option value="cheese">Cheese</option>
                                        <option value="tomatoes">Tomatoes</option>
                                        <option value="mozarella">Mozzarella</option>
                                        <option value="mushrooms">Mushrooms</option>
                                        <option value="pepperoni">Pepperoni</option>
                                        <option value="onions">Onions</option>
                                    </select>

<?php
    $this->headLink()->appendStylesheet($this->baseUrl('/front/css/bootstrap-multiselect.css'));
    $this->inlineScript()->appendFile($this->baseUrl('/front/js/bootstrap-multiselect.js'));
?>


<!-- Initialize the plugin: -->
<script type="text/javascript">
    $(document).ready(function() {
        $('#example-getting-started').multiselect();
    });
</script>