    <main>
        <section class="smallNav"> 
            <div class="container-fluid">
                <div class="row">
                    <div class="col-xs-12 text-center">
                        <h2><a href="about.html">About</a></h2>
                    </div>
                    <div class="col-xs-12 text-center">
                        <ul class="simplefilterFirst">     
                            <li role="presentation" class="active"><a href="index.html">HOMEPAGE</a></li>
                            <li role="presentation"><a href="contacts.html">CONTACT</a></li>                   
                        </ul> 
                    </div>
                </div>  
            </div> 
        </section>

        <section class="map">
            <iframe src="https://www.google.com/maps/embed?pb=!1m14!1m12!1m3!1d22638.214543463546!2d20.42206543162841!3d44.826111204134136!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!5e0!3m2!1sen!2srs!4v1470981890279" frameborder="0" style="border:0" allowfullscreen></iframe>
        </section>

        <section class="informations">
            <div class="container">
                <div class="row">
                    <article class="col-xs-12 col-sm-6 col-md-3 address">
                        <h2>ADDRESS</h2>
                        <p>2661 Mapleview Drive</p>
                        <p>Tarpon Springs, FL 34689</p>
                    </article>
                    <article class="col-xs-12 col-sm-6 col-md-3 hours">
                        <h2>HOURS</h2>
                        <p>Weekdays: <span>9:00-18:00</span> </p>
                        <p>Saturday: <span>11:00-15:00</span></p>
                    </article>
                    <article class="col-xs-12 col-sm-6 col-md-3 phone">
                        <h2>PHONE</h2>
                        <p>Phone:<span> 727-937-3797</span></p>
                        <p>   Fax: <span>863-256-5533</span></p>                      
                    </article>
                    <article class="col-xs-12 col-sm-6 col-md-3 email">
                        <h2>EMAIL</h2>
                        <p><a href="mailto:example@mail.com">example@mail.com</a></p>                     
                    </article>
                </div> 
            </div>
        </section>
        <section class="contactInfo">
            <div class="container-fluid">
                <div class="row text-center ">
                    <div class="col-xs-12 col-md-offset-4 col-md-4">
                        <h2>Contact us &<br>  </h2>
                        <p>get free quote about organic food</p>                  
                        <form>
                            <div class="form-group">
                                <label for="exampleInputEmail1"></label>
                                <input type="text" class="form-control" id="exampleInputName" placeholder="Full Name">
                            </div>
                            <div class="form-group">
                                <label for="exampleInputEmail1"></label>
                                <input type="email" class="form-control" id="exampleInputEmail1" placeholder="E-mail Address">
                            </div>
                            <div class="form-group">
                                <label for="exampleInputEmail1"></label>
                                <input type="tel" class="form-control" id="exampleInputPhone" placeholder="Phone Number">
                            </div>
                            <textarea class="form-control-static"  rows="5" placeholder="Message"></textarea>

                            <button type="submit" class="btn btn-default">SUBMIT MESSAGE</button>
                        </form>                                                                                                 
                    </div> 
                </div>
            </div>
        </section>
    </main>