    <?php
		//print_r(strlen($this->contactInfo['map_id'])); die();
		$sitemapPage = $this->sitemapPage;
		$sitemapPageBreadcrumbs = $this->sitemapPageBreadcrumbs;
	?>

	<main>
		
        <section class="smallNav"> 
            <div class="container-fluid">
                <div class="row">
                    <div class="col-xs-12 text-center">
                        <h2><?php echo $this->escape($sitemapPage['title']); ?></h2>
                    </div>
                    <div class="col-xs-12 text-center">
                        <ul class="simplefilterFirst">     
							<li role="presentation" class="active"><a href="<?php echo $this->baseUrl('/'); ?>">NASLOVNA</a></li>
							<?php foreach ($sitemapPageBreadcrumbs as $sitemapPage) { ?>
								<li role="presentation"><a href="<?php echo $this->sitemapPageUrl($sitemapPage['id']);?>"><?php echo $this->escape($sitemapPage['title']); ?></a></li>
							<?php }?>
                        </ul> 
                    </div>
                </div>  
            </div> 
        </section>

        <section class="map">
			<div class="row col-md-10 col-md-offset-1" id="map" style=" height: 400px"></div>
<!--            <iframe src="https://www.google.com/maps/embed?pb=!1m14!1m12!1m3!1d22638.214543463546!2d20.42206543162841!3d44.826111204134136!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!5e0!3m2!1sen!2srs!4v1470981890279" frameborder="0" style="border:0" allowfullscreen></iframe>-->
        </section>

        <section class="informations">
            <div class="container">
                <div class="row">
                    <article class="col-xs-12 col-sm-6 col-md-3 address">
                        <h2>ADDRESS</h2>
                        <p><?php echo $this->contactInfo['address'] . ' ' . $this->contactInfo['address_number']; ?></p>
						<p><?php //echo $this->contactInfo['city']; ?></p>
					</article>
                    <article class="col-xs-12 col-sm-6 col-md-3 hours">
                        <h2>HOURS</h2>
                        <p>Weekdays: <span><?php echo $this->contactInfo['hours']; ?></span></p>
                        <p>Weekend: <span>closed</span></p>
                    </article>
                    <article class="col-xs-12 col-sm-6 col-md-3 phone">
                        <h2>PHONE</h2>
                        <p>Phone:<span><?php echo $this->contactInfo['phone']; ?></span></p>
						<?php if (isset($this->contactInfo['fax'])) { ?>
							<p>Fax: <span><?php echo $this->contactInfo['fax']; ?></span></p>             
						<?php } ?>
                    </article>
                    <article class="col-xs-12 col-sm-6 col-md-3 email">
                        <h2>EMAIL</h2>
                        <p><a href="mailto:<?php echo $this->contactInfo['email']; ?>"><?php echo $this->contactInfo['email']; ?></a></p>                     
                    </article>
                </div> 
            </div>
        </section>
        <section class="contactInfo">
            <div class="container-fluid">
                <div class="row text-center ">
					<h2>Contact us &<br>  </h2>
					<p>get free quote about organic food</p>
                    
                        <form>
							<div class="col-xs-12 col-md-offset-3 col-md-3">
								<div class="form-group">
									<label for="exampleInputEmail1"></label>
									<input type="text" class="form-control" id="exampleInputName" placeholder="Full Name">
								</div>
								<div class="form-group">
									<label for="exampleInputEmail1"></label>
									<input type="email" class="form-control" id="exampleInputEmail1" placeholder="E-mail Address">
								</div>
								<div class="form-group">
									<label for="exampleInputEmail1"></label>
									<input type="tel" class="form-control" id="exampleInputPhone" placeholder="Phone Number">
								</div>
							</div>
							<div class="col-xs-12 col-md-offset-0 col-md-3">
								<textarea class="form-control-static"  rows="8" placeholder="Message"></textarea>
							</div>
							<div class="col-xs-12 col-md-offset-5 col-md-2">
								<button type="submit" class="btn btn-default">SUBMIT MESSAGE</button>
							</div>
						</form>                                                                                                 
                    
                </div>
            </div>
        </section>
    </main>

<?php
    //$this->headLink()->appendStylesheet($this->baseUrl(''));
    $this->inlineScript()->appendFile('http://ajax.googleapis.com/ajax/libs/jquery/1.11.0/jquery.min.js');
	$this->inlineScript()->appendFile('https://maps.googleapis.com/maps/api/js?key=AIzaSyCl63DjLjiuUgfMShPAK0Jy5peunCa9NZ4&libraries=places&callback=initMap');
?>

<?php $this->inlineScript()->captureStart(); ?>
	<script>
		var latitude = 0;
		var longitude = 0;
		var place_id;  
		var placeSearch, autocomplete;

		var componentForm = {
			street_number: 'short_name',
			route: 'long_name',
			locality: 'long_name',
			country: 'long_name'
		};

		var map;
		var marker;

		$("#findmyPostcode").click(function (event) {

			var result = 0;

			$(".alert").hide();

			event.preventDefault();

			$(".alert").hide();
			$.ajax({
				type: "GET",
				url: "https://maps.googleapis.com/maps/api/geocode/xml?address="+encodeURIComponent($('#address').val())+"&key=AIzaSyCl63DjLjiuUgfMShPAK0Jy5peunCa9NZ4",
				dataType: "xml",
				success: processXML,
				error: error

			});

			function error() {
				$("#fail2").fadeIn();
			}

			function processXML(xml) {

				$(xml).find("location").each(function () {
					latitude = $(this).find("lat").text();
					//alert(lat);
					longitude = $(this).find("lng").text();
					lng = $(this).find("lng").text();
					$("#success").html("Lat: " + $(this).find("lat").text() + " Lng: " + $(this).find("lng").text() + " place id: " + $(xml).find("place_id").text()).fadeIn();
					result = 1;

					var coordinates = new google.maps.LatLng(latitude, longitude);
					map.setCenter(coordinates);

					marker.setPosition(coordinates);

				});


				if (result == 0) {
					$("#fail").fadeIn();
				}

			}       
		});


		function initMap() {

			var myLatLng = {lat: 44.831213, lng: 20.410245};

			if (latitude && longitude) {
				myLatLng = {
					lat: latitude, 
					lng: longitude
				};
			}

			map = new google.maps.Map(document.getElementById('map'), {
				center: myLatLng,
				zoom: 15
			});

			marker = new google.maps.Marker({
				position: myLatLng,
				map: map,
				animation: google.maps.Animation.DROP,
				title: 'Cubes School'
			});


			marker.addListener('click', toggleBounce);

			var options = {
				types: ['(cities)'],
				componentRestrictions: {country: 'rs'}
			};


			autocomplete = new google.maps.places.Autocomplete(
					(document.getElementById('address')),
					{types: ['geocode'], componentRestrictions: {country: 'rs'}}
			);
			autocomplete.addListener('place_changed', fillInAddress);

		}

		function toggleBounce() {
			if (marker.getAnimation() !== null) {
				marker.setAnimation(null);
			} else {
				marker.setAnimation(google.maps.Animation.BOUNCE);
			}
		}

		function fillInAddress() {
			// Get the place details from the autocomplete object.
			var place = autocomplete.getPlace();

			for (var component in componentForm) {
				document.getElementById(component).innerHTML = '';
				document.getElementById(component).disabled = false;
			}

			// Get each component of the address from the place details
			// and fill the corresponding field on the form.
			for (var i = 0; i < place.address_components.length; i++) {
				var addressType = place.address_components[i].types[0];
				if (componentForm[addressType]) {
					var val = place.address_components[i][componentForm[addressType]];
					document.getElementById(addressType).innerHTML = val;
				}
			}
		}addListener('place_changed', fillInAddress);

		}
	</script>
<?php $this->inlineScript()->captureEnd(); ?>
