    <?php
		//print_r(strlen($this->contactInfo['map_id'])); die();
		$sitemapPage = $this->sitemapPage;
		$sitemapPageBreadcrumbs = $this->sitemapPageBreadcrumbs;
	?>

	<main>
		
        <section class="smallNav"> 
            <div class="container-fluid">
                <div class="row">
                    <div class="col-xs-12 text-center">
                        <h2><?php echo $this->escape($sitemapPage['title']); ?></h2>
                    </div>
                    <div class="col-xs-12 text-center">
                        <ul class="simplefilterFirst">     
							<li role="presentation" class="active"><a href="<?php echo $this->baseUrl('/'); ?>">NASLOVNA</a></li>
							<?php foreach ($sitemapPageBreadcrumbs as $sitemapPage) { ?>
								<li role="presentation"><a href="<?php echo $this->sitemapPageUrl($sitemapPage['id']);?>"><?php echo $this->escape($sitemapPage['title']); ?></a></li>
							<?php }?>
                        </ul> 
                    </div>
                </div>  
            </div> 
        </section>

        <section class="map">
			<div class="row col-md-10 col-md-offset-1" id="map" style=" height: 400px"></div>
<!--            <iframe src="https://www.google.com/maps/embed?pb=!1m14!1m12!1m3!1d22638.214543463546!2d20.42206543162841!3d44.826111204134136!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!5e0!3m2!1sen!2srs!4v1470981890279" frameborder="0" style="border:0" allowfullscreen></iframe>-->
        </section>

        <section class="informations">
            <div class="container">
                <div class="row">
                    <article class="col-xs-12 col-sm-6 col-md-3 address">
                        <h2>ADDRESS</h2>
                        <p><?php echo $this->contactInfo['address'] . ' ' . $this->contactInfo['address_number']; ?></p>
						<p><?php //echo $this->contactInfo['city']; ?></p>
					</article>
                    <article class="col-xs-12 col-sm-6 col-md-3 hours">
                        <h2>HOURS</h2>
                        <p>Weekdays: <span><?php echo $this->contactInfo['hours']; ?></span></p>
                        <p>Weekend: <span>closed</span></p>
                    </article>
                    <article class="col-xs-12 col-sm-6 col-md-3 phone">
                        <h2>PHONE</h2>
                        <p>Phone:<span><?php echo $this->contactInfo['phone']; ?></span></p>
						<?php if (isset($this->contactInfo['fax'])) { ?>
							<p>Fax: <span><?php echo $this->contactInfo['fax']; ?></span></p>             
						<?php } ?>
                    </article>
                    <article class="col-xs-12 col-sm-6 col-md-3 email">
                        <h2>EMAIL</h2>
                        <p><a href="mailto:<?php echo $this->contactInfo['email']; ?>"><?php echo $this->contactInfo['email']; ?></a></p>                     
                    </article>
                </div> 
            </div>
        </section>
        <section class="contactInfo">
            <div class="container-fluid">
                <div class="row text-center ">
					<h2>Contact us &<br>  </h2>
					<p>get free quote about organic food</p>
                    
                        <form>
							<div class="col-xs-12 col-md-offset-3 col-md-3">
								<div class="form-group">
									<label for="exampleInputEmail1"></label>
									<input type="text" class="form-control" id="exampleInputName" placeholder="Full Name">
								</div>
								<div class="form-group">
									<label for="exampleInputEmail1"></label>
									<input type="email" class="form-control" id="exampleInputEmail1" placeholder="E-mail Address">
								</div>
								<div class="form-group">
									<label for="exampleInputEmail1"></label>
									<input type="tel" class="form-control" id="exampleInputPhone" placeholder="Phone Number">
								</div>
							</div>
							<div class="col-xs-12 col-md-offset-0 col-md-3">
								<textarea class="form-control-static"  rows="8" placeholder="Message"></textarea>
							</div>
							<div class="col-xs-12 col-md-offset-5 col-md-2">
								<button type="submit" class="btn btn-default">SUBMIT MESSAGE</button>
							</div>
						</form>                                                                                                 
                    
                </div>
            </div>
        </section>
    </main>
	<script src="//ajax.googleapis.com/ajax/libs/jquery/1.11.0/jquery.min.js"></script> 
	<script type="text/javascript">
		<?php $this->inlineScript()->captureStart(); ?>
			function initMap() {
				var myLatLng = {lat: 44.831213, lng: 20.410245};

				if (latitude && longitude) {
					myLatLng = {
						lat: latitude, 
						lng: longitude
					};
				}

				map = new google.maps.Map(document.getElementById('map'), {
					center: myLatLng,
					zoom: 15
				});

//				marker = new google.maps.Marker({
//					position: myLatLng,
//					map: map,
//					animation: google.maps.Animation.DROP,
//					title: 'Cubes School'
//				});
				

			}
		<?php $this->inlineScript()->captureEnd(); ?>
	</script>